# setup is at https://travis-ci.com

language: python
dist: xenial

notifications:
  email: false

# Instead of using a build matrix, each job we want to run is explicitly
# defined below. Why not use the matrix? So many specific jobs are being
# included that it actually is easier to follow making all jobs explicit.
jobs:
  include:
    # For MacOS, unfortunately there is no native Python support from Travis.
    # That complexity is handled internally to the ci-prepare-environment.bash
    # script that is called in the before_install.
    - {os: osx, env: ICU_VERSION=55.2, language: sh, python: 3.8}
    - {os: osx, env: ICU_VERSION=67.1, language: sh, python: 3.8}
    - {os: osx, env: ICU_VERSION=68.1, language: sh, python: 3.9}

    # # Same story for Windows (currently not working).
    # - {os: windows, env: ICU_VERSION=55.2, language: sh, python: 3.9}
    # - {os: windows, env: ICU_VERSION=67.1, language: sh, python: 3.9}
    # - {os: windows, env: ICU_VERSION=68.1, language: sh, python: 3.9}

    # Run ICU 68 on every Python version.
    - {env: ICU_VERSION=68.1, python: 2.7}
    - {env: ICU_VERSION=68.1, python: 3.5}
    - {env: ICU_VERSION=68.1, python: 3.6}
    - {env: ICU_VERSION=68.1, python: 3.7}
    - {env: ICU_VERSION=68.1, python: 3.8}
    - {env: ICU_VERSION=68.1, python: 3.9}
    - {env: ICU_VERSION=68.1, python: 3.8}
    - {env: ICU_VERSION=68.1, python: 3.9}

    # Run ICU 55 on every Python version.
    - {env: ICU_VERSION=55.2, python: 2.7}
    - {env: ICU_VERSION=55.2, python: 3.5}
    - {env: ICU_VERSION=55.2, python: 3.6}
    - {env: ICU_VERSION=55.2, python: 3.7}
    - {env: ICU_VERSION=55.2, python: 3.8}
    - {env: ICU_VERSION=55.2, python: 3.9}

    # Run all other ICU versions only on Python 3.9
    - {env: ICU_VERSION=50.2, python: 3.9}
    - {env: ICU_VERSION=51.3, python: 3.9}
    # - {env: ICU_VERSION=52.2, python: 3.9}  # gcc error ‘-Qunused-arguments’
    - {env: ICU_VERSION=53.2, python: 3.9}
    - {env: ICU_VERSION=54.2, python: 3.9}
    - {env: ICU_VERSION=56.2, python: 3.9}
    - {env: ICU_VERSION=57.2, python: 3.9}
    - {env: ICU_VERSION=58.3, python: 3.9}
    - {env: ICU_VERSION=59.2, python: 3.9}
    - {env: ICU_VERSION=60.3, python: 3.9}
    - {env: ICU_VERSION=61.2, python: 3.9}
    - {env: ICU_VERSION=62.2, python: 3.9}
    - {env: ICU_VERSION=63.2, python: 3.9}
    - {env: ICU_VERSION=64.2, python: 3.9}
    - {env: ICU_VERSION=65.1, python: 3.9}
    - {env: ICU_VERSION=66.1, python: 3.9}
    - {env: ICU_VERSION=67.1, python: 3.9}

    # Run a few ICU versions on arm64 + Python 3
    - {arch: arm64, env: ICU_VERSION=55.2, python: 3.7}
    - {arch: arm64, env: ICU_VERSION=66.1, python: 3.7}
    - {arch: arm64, env: ICU_VERSION=55.2, python: 3.8}
    - {arch: arm64, env: ICU_VERSION=64.2, python: 3.8}
    - {arch: arm64, env: ICU_VERSION=66.1, python: 3.8}
    - {arch: arm64, env: ICU_VERSION=63.2, python: 3.8}
    - {arch: arm64, env: ICU_VERSION=55.2, python: 3.8}
    # - {arch: arm64, env: ICU_VERSION=67.1, python: 3.8}  # uint8_t errors
    - {arch: arm64, env: ICU_VERSION=68.1, python: 3.8}
    - {arch: arm64, env: ICU_VERSION=55.2, python: 3.9}
    - {arch: arm64, env: ICU_VERSION=68.1, python: 3.9}

    - stage: build wheels
      install: python3 -m pip install cibuildwheel==1.6.4
      script:
        # build the wheels, put them into './wheelhouse'
        - python3 -m cibuildwheel --output-dir wheelhouse

before_install:
  - bash ci-prepare-environment.bash

install:
  - export PYICU_LIBRARIES="icui18n:icuuc:icudata"
  - export PYICU_INCLUDES="$HOME/icu4c/include"
  - export PYICU_LFLAGS="-L$HOME/icu4c/lib"
  - if [ ${ICU_VERSION%.*} -lt 58 ]; then export PYICU_LIBRARIES="${PYICU_LIBRARIES}:icule"; fi
  - PATH="$HOME/icu4c/bin:${PATH}" pip install . pytest

script:
  - LD_LIBRARY_PATH="$HOME/icu4c/lib" DYLD_LIBRARY_PATH="$HOME/icu4c/lib" py.test


cache:
  ccache: true
  pip: true
  timeout: 1000
  directories:
   - $HOME/.pyenv_cache  # for macos
   - $HOME/icu4c
